<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Expires" content="Fri, Jan 01 1900 00:00:00 GMT">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Lang" content="en">
<meta name="author" content="">
<meta http-equiv="Reply-to" content="@.com">
<meta name="generator" content="PhpED 5.8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="creation-date" content="01/01/2009">
<meta name="revisit-after" content="15 days">
<?php echo $this->headTitle(); ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/public/css/my.css">
</head>
<body>
<div class="header">
    <span class="logo-1">Philo</span>
    <span class="logo-2">Tech</span>
</div>

<div id="main-content">
    <div id="menu">
        <h2>Menu</h2>
        <hr/>
        <ul>
            <li><a href="">Home</a></li>
            <li><a href="">Add New Employee</a></li>
            <li><a href="">Find Employee</a></li>
        </ul>
    </div>
    <div id="content">
        <?php echo $this->layout()->content; ?>
    </div>
</div>
<div class="footer">
    <p>Copyright | 2013</p>
</div>
</body>
</html>
