<!DOCTYPE HTML>
<!--
	TXT 2.0 by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Left Sidebar - TXT by HTML5 UP</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,700|Open+Sans+Condensed:700" rel="stylesheet" />
		<script src="<?php echo $this->baseUrl() ?>/public/js/jquery-1.9.1.min.js"></script>
		<script src="<?php echo $this->baseUrl() ?>/public/js/config.js"></script>
		<script src="<?php echo $this->baseUrl() ?>/public/js/skel.min.js"></script>
		<script src="<?php echo $this->baseUrl() ?>/public/js/skel-ui.min.js"></script>
		
			<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/css/skel-noscript.css" />
			<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/css/style.css" />
			<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/public/css/style-desktop.css" />
		
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><link rel="stylesheet" href="css/ie8.css" /><![endif]-->
		<!--[if lte IE 7]><link rel="stylesheet" href="css/ie7.css" /><![endif]-->
	</head>
	<body>


		<!-- Nav -->
			<nav id="nav" class="skel-ui-fixed">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li class="current_page_item"><a href="left-sidebar.html">Left Sidebar</a></li>
					<li><a href="right-sidebar.html">Right Sidebar</a></li>
					<li><a href="no-sidebar.html">No Sidebar</a></li>
				</ul>
			</nav>
		<!-- /Nav -->
		
		<!-- Main -->
			<div id="main-wrapper">
				<div id="main" class="container">
					<div class="row">
						<div class="9u skel-cell-mainContent">
							<div class="content content-right">
							
								<!-- Content -->
						
									<?php echo $this->layout()->content; ?>

								<!-- /Content -->
								
							</div>
						</div>
					</div>
					<div class="row">
						<div class="12u">

							<!-- Features -->
								<section class="is-features">
									<h2 class="major"><span>Valid Commands</span></h2>
									<div>
										<div class="row">
											<div class="3u">
												
												<!-- Feature -->
													<section class="is-feature">
														<a href="#" class="image image-full"><img src="images/pic01.jpg" alt="" /></a>
														<h3><a href="#">Look Up</a></h3>
														<p>
															Phasellus quam turpis, feugiat sit amet ornare in, a hendrerit in 
															lectus dolore. Praesent semper mod quis eget sed etiam eu ante risus.
														</p>
													</section>
												<!-- /Feature -->
										
											</div>
											<div class="3u">
												
												<!-- Feature -->
													<section class="is-feature">
														<a href="#" class="image image-full"><img src="images/pic02.jpg" alt="" /></a>
														<h3><a href="#">Look Down</a></h3>
														<p>
															Phasellus quam turpis, feugiat sit amet ornare in, a hendrerit in 
															lectus dolore. Praesent semper mod quis eget sed etiam eu ante risus.
														</p>
													</section>
												<!-- /Feature -->
										
											</div>
											<div class="3u">
												
												<!-- Feature -->
													<section class="is-feature">
														<a href="#" class="image image-full"><img src="images/pic03.jpg" alt="" /></a>
														<h3><a href="#">Examine Room</a></h3>
														<p>
															Phasellus quam turpis, feugiat sit amet ornare in, a hendrerit in 
															lectus dolore. Praesent semper mod quis eget sed etiam eu ante risus.
														</p>
													</section>
												<!-- /Feature -->
										
											</div>
											<div class="3u">
												
												<!-- Feature -->
													<section class="is-feature">
														<a href="#" class="image image-full"><img src="images/pic04.jpg" alt="" /></a>
														<h3><a href="http://getlamp.com">Get Lamp</a></h3>
														<p>
															Phasellus quam turpis, feugiat sit amet ornare in, a hendrerit in 
															lectus dolore. Praesent semper mod quis eget sed etiam eu ante risus.
														</p>
													</section>
												<!-- /Feature -->
										
											</div>
										</div>
									</div>
								</section>
							<!-- /Features -->

						</div>
					</div>
				</div>
			</div>
		<!-- /Main -->

		<!-- Footer -->
			<footer id="footer" class="container">
				<div class="row">
					<div class="12u">

						<!-- About -->
							<section>
								<h2 class="major"><span>What's this about?</span></h2>
								<p>
									This is <a href="http://html5up.net/txt/">TXT</a>, a free site template designed by
									<a href="http://n33.co">n33</a> for <a href="http://html5up.net/">HTML5 UP</a>.
									It's built on the <a href="http://skeljs.org">skel.js</a> framework, uses well-thought out
									HTML5 and CSS3, and is fully responsive making it a great starting point for your own
									projects. And, like everything else we make, it's also free to use for pretty much any
									personal or commercial work under the <a href="http://html5up.net/license/">Creative Commons Attribution</a>
									license, so go ahead and use it &ndash; just don't forget to credit us!
								</p>
							</section>
						<!-- /About -->

					</div>
				</div>
				<div class="row">
					<div class="12u">

						<!-- Contact -->
							<section>
								<h2 class="major"><span>Get in touch</span></h2>
								<ul class="contact">
									<li><a href="#" class="facebook">Facebook</a></li>
									<li><a href="http://twitter.com/n33co" class="twitter">Twitter</a></li>
									<li><a href="http://n33.co/feed/" class="rss">RSS</a></li>
									<li><a href="http://dribbble.com/n33" class="dribbble">Dribbble</a></li>
									<li><a href="#" class="linkedin">LinkedIn</a></li>
									<li><a href="#" class="googleplus">Google+</a></li>
								</ul>
							</section>
						<!-- /Contact -->
					
					</div>
				</div>
				<div class="row">

					<!-- Copyright -->
						<div id="copyright">
							&copy; 2012 Untitled Something | Images: <a href="http://fotogrph.com">fotogrph</a> + <a href="http://iconify.it">Iconify.it</a> | Design: <a href="http://html5up.net/">HTML5 UP</a>
						</div>
					<!-- /Copyright -->

				</div>
			</footer>
		<!-- /Footer -->

	</body>
</html>